# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.


HEADERS += ./qadvancedtableviewplugin.h \
    ./qaivdesignercollection.h
SOURCES += ./qadvancedtableviewplugin.cpp \
    ./qaivdesignercollection.cpp
RESOURCES += ./qaivdesigner.qrc
