# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.

HEADERS += ./mainwindow.h \
    ./spinboxitemdelegate.h
SOURCES += ./main.cpp \
    ./mainwindow.cpp \
    ./spinboxitemdelegate.cpp
FORMS += ./mainwindow.ui
RESOURCES += example.qrc
