# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

QT += core gui
CONFIG += qtestlib debug console
CONFIG -= app_bundle
TEMPLATE = app
TARGET = test_qadvancedtableview

win32 {
    DESTDIR = ../../bin/Win32/Debug
    DEFINES += QT_LARGEFILE_SUPPORT QT_DLL
    LIBS += -l$(DESTDIR)/qaivlib
}
else {
    DESTDIR = ../../Debug
    LIBS += -L./../../Debug -lqaivlib
}

INCLUDEPATH += . \
    ./GeneratedFiles/Debug \
    ./../../qaivlib
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles

include(test_qadvancedtableview.pri)
